apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: eureka-deployment
spec:
  selector:
    matchLabels:
      app: eureka
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: mkubik/eureka
        ports:
        - containerPort: 8761
        
apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  selector:
    app: eureka
  ports:
  - protocol: TCP
    port: 8761
    targetPort: 8761
           